### ISSUE TITLE
What is the Gothic Dataset?

### ISSUE THREAD

**Issue by Flux9665** [lexkoro/GothicTTS#1]
I love the game, so I would like to include this dataset into my collection of datasets to train TTS models on. Searching for it online gave me no results though. Can you point me to where I can find this Gothic Dataset?

**Comment by lexkoro** [comment]
Hi, I extracted the data from the games myself.

**Comment by Flux9665** [comment]
That's cool! Can you share the dataset somehow?

**Comment by lexkoro** [comment]
I currently don't have access to it. But you can contact me by e-mail or add me on discord (resser).
